### ISSUE TITLE
DataSetsError while loading mushrooms

### ISSUE THREAD

**Issue by shivendra90** [DistrictDataLabs/yellowbrick#972]
**Describe the bug**
While loading the mushrooms dataset. I receive this error:
```python
DataSetsError: the download dataset was improperly packaged without meta.json
```

**To Reproduce**

```python
# Import the datasets module
from yellowbrick.datasets import load_mushroom
x ,y = load_mushroom()

DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!
```

**Dataset**
Did you use a specific dataset to produce the bug? Yes.
 Where can we access it? The inbuilt datasets module.

**Expected behavior**
The mushrooms dataset should load as normal.

**Traceback**

```
  File "<ipython-input-11-35aea394a3b4>", line 1, in <module>
    X, y = load_mushroom()

  File "/Users/Shiv/anaconda3/lib/python3.7/site-packages/yellowbrick/datasets/loaders.py", line 275, in load_mushroom
    return _load_dataset("mushroom", data_home, return_dataset)

  File "/Users/Shiv/anaconda3/lib/python3.7/site-packages/yellowbrick/datasets/loaders.py", line 62, in _load_dataset
    return data.to_data()

  File "/Users/Shiv/anaconda3/lib/python3.7/site-packages/yellowbrick/datasets/base.py", line 177, in to_data
    return self.to_pandas()

  File "/Users/Shiv/anaconda3/lib/python3.7/site-packages/yellowbrick/datasets/base.py", line 222, in to_pandas
    "the downloaded dataset was improperly packaged without meta.json "
```

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS 10.14.2
 - Python Version [e.g. 2.7, 3.6, miniconda] 3.7
 - Yellowbrick Version [e.g. 0.7] 1.0

**Additional context**

**Comment by bbengfort** [comment]
Hi @shivendra90 - thanks for the note. I think that you have an earlier version of the dataset downloaded. Please run the following:

```
$ python -m yellowbrick.download --cleanup 
```

This will delete the existing datasets and redownload them and should solve the problem. Let me know if you have any further questions!

**Comment by adeelahuma** [comment]
Hi @bbengfort , 
I am also running into issue for bike share data. I did follow the cleanup step that you suggested but I am still getting the error: 

> DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!

**Comment by bbengfort** [comment]
Hi @adeelahuma what version of Yellowbrick, Python, and OS are you using? Would you mind also trying to uninstall and reinstall yellowbrick as follows:

```
$ pip uninstall yellowbrick
$ pip install -U yellowbrick
```
